---
title: "Transmisión intergeneracional y sensación de justicia en la escuela."
#csl: "../input/bib/apa6.csl"
#bibliography: "../input/bib/zlibrary.bib"
author: " "
output:
    bookdown::html_document2:
            smart: false
            includes:
              in_header: head_github-activity.html
            number_sections: false          
---

> Este sitio web contiene el material para reproducir una investigación sobre la transimición intergeneracional de la perspeción de meritocacia. 

Last update: `r format(Sys.time(), "%A %d %B %Y %X")`

### Autores:

- Juan Carlos Castillo, Departamento de Sociología, Universidad de Chile. [juancastillov@uchile.cl](juancastillov@uchile.cl), [jc-castillo.com](http://jc-castillo.com/)
- Julio Iturra, coordinador
- Francisco Meneses, asistente y tesista de investigación
- Martín Venegas, ayudante de investigación

### Resumen:

En base a literatura anterior este trabajo estudia la socialización de creencias meritocracias centrandoce en la transmición familiar y las experiencias de justicia en la escuela en base a una muestra de estudiantes chilenos (N= 700, final wave).

- Pre-analysis: Este proyecto cuenta con un preregistro de las hipótesis en la plataforma Open Science Framework (OSF), disponible en este [link](https://osf.io/ejq39/)  

¿Cómo citar el pre-registro?: Castillo, J. C., Miranda, D., Iturra, J. C., Meneses, F. J., & Venegas, M. (2021, January 31). Legitimidad. Retrieved from osf.io/ejq39


### Estructura del sitio web:

- The tabs follow the logic of the [IPO protocol](https://github.com/juancarloscastillo/ipo) for academic workflows, based on three main components = **I**nput -> **P**roduction -> **O**utput. Here we show only one the main parts of each component: Data -> Analysis -> Paper. The complete reproducible files are in the [Github repo: https://juancarloscastillo.github.io/merit-scale/](https://juancarloscastillo.github.io/merit-scale/)

  - _Preparación_: pre-processing and general descriptives
  - _Análisis_: regresiones multinivel
  - _Articulo_: final output

### Reproducibilidad y documetanción

El repositorio del proyecto en Github está estructurado según el [protocolo de reproducibilidad IPO](https://juancarloscastillo.github.io/ipo/).

<br>

## [Github activity feed](https://github.com/juancarloscastillo/github-activity)

<div id="feed"></div>

<br>

## References
